" 'set encoding' and then 'scriptencoding'
" https://rbtnn.hateblo.jp/entry/2014/12/28/010913
set encoding=utf-8
scriptencoding utf-8
set fileencodings=ucs-bom,utf-8,iso-2022-jp,euc-jp,cp932

set number
set wrap
set list
set listchars=tab:»\ ,trail:-,extends:»,precedes:«,nbsp:%

nnoremap ,f :<C-u>e %:p:h<CR>
nnoremap ,b :<C-u>ls<CR>:buf 
" very magic - get rid of vim's obscure regexp
nnoremap /  /\v

" visible zenkaku-space
" https://vim-jp.org/vim-users-jp/2009/07/12/Hack-40.html
augroup highlightIdegraphicSpace
  autocmd!
  autocmd Colorscheme * highlight IdeographicSpace term=underline ctermbg=DarkGreen guibg=DarkGreen
  autocmd VimEnter,WinEnter * match IdeographicSpace /　/
augroup END
highlight SpecialKey guifg=DarkGreen
colorscheme default

let g:netrw_banner=0
